[devshell]
name = "Advent of Code 2023"
packages = ["zig-shell-completions", "direnv", "gh"]
packagesFrom = ["direnv"]

[[commands]]
help = "builds the project"
name = "zb"
command = "zig build"

[[commands]]
help = "run day X of the advent of code"
name = "zr"
command = "zig build run_day$1"

[[commands]]
help = "test the project"
name = "zt"
command = "zig build test"

[[commands]]
package = "nixpkgs-fmt"
category = "formatters"
[[commands]]
package = "alejandra"
category = "formatters"

[[commands]]
help = "github utility"
name = "gh"
package = "gh"
category = "utilites"